manifest = "1881fbe5ad0f619b27fb131202709d5b3b4aa24a8ceddea3daa4bcf8b69ad489"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.24.0" ]
revision = "37278170bcbe6e22f6eebed0d33d5df4e0d015e1"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.24.0" ]
revision = "36d22132d39fc31e27c7ba1f61d91b294e12aa78"
