manifest = "e03a8a262e3f058f6bb3621c738e021c4aeb40f0b667ebb8996360f22692339b"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.38.0" ]
revision = "f129de05f396dc4d6e5460a69f648766659d4e09"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.38.0" ]
revision = "052bc304465323f02bea64dca87d3db7c07b457b"
